services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatgpt-clone-backend
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatgpt-clone-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
