[project]
name = "server"
version = "0.1.0"
description = "The backend service is a Django REST framework to communicate with Azure OpenAI GPT-4o model."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-cors-headers>=4.4.0",
    "django-stubs>=5.1.0",
    "django>=5.1.2",
    "djangorestframework-stubs>=3.15.1",
    "djangorestframework>=3.15.2",
    "drf-spectacular>=0.27.2",
    "loguru>=0.7.2",
    "openai>=1.52.2",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]

[tool.uv]
dev-dependencies = [
    "coverage>=7.6.7",
    "crosszip>=1.0.0",
    "locust>=2.32.0",
    "mypy>=1.13.0",
    "pytest-django>=4.9.0",
    "pytest-random-order>=1.1.1",
    "pytest>=8.3.3",
    "ruff>=0.8.1",
]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
preview = true
#select = ["ALL"]
ignore = ["COM812", "CPY", "D100", "D203", "D212", "DOC502"]

[tool.ruff.lint.per-file-ignores]
"test_*.py" = [
    # docstring requirements
    "D",
    "DOC",
    # tests can have asserts
    "S101",
]

[tool.ruff.format]
preview = true

[tool.coverage.run]
omit = [
    # boilerplate generated by Django
    "chatgptserver/chatgptserver/*",
    "chatgptserver/manage.py",
    # no need to check openai implementation
    "chatgptserver/api/utils.py",
]

[tool.pytest.ini_options]
addopts = [
    # error on using unregistered marker
    "--strict-markers",
    # show extra test summary info for everything
    "-ra",
]
xfail_strict = true
python_files = ["test_*.py", "test-*.py", "tests.py", "test.py"]
