openapi: 3.0.3
info:
  title: chatgptserver
  version: 1.0.0
  description: Backend API for ChatGPT
paths:
  /api/v1/chat/{model}/:
    post:
      operationId: v1_chat_create
      description: Generate a chat response based on the provided prompt and settings.
      parameters:
      - in: path
        name: model
        schema:
          type: string
          enum:
          - gpt-4o
          - gpt-4o-mini
        description: Model to use for response generation
        required: true
      - in: query
        name: temperature
        schema:
          type: string
          enum:
          - BALANCED
          - CREATIVE
          - DETERMINISTIC
          default: BALANCED
        description: 'Temperature for response generation: 0.2 (deterministic), 0.7
          (balanced), 0.9 (creative)'
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChatRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChatRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssistantResponse'
          description: ''
components:
  schemas:
    AssistantResponse:
      type: object
      properties:
        response:
          type: string
      required:
      - response
    ChatRequest:
      type: object
      properties:
        prompt:
          type: string
      required:
      - prompt
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
