name: prek

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    uses: IndrajeetPatil/workflows/.github/workflows/pre-commit.yaml@main

  ls-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install ls-lint v2.3.1
        run: |
          curl -fsSLO "https://github.com/loeffel-io/ls-lint/releases/download/v2.3.1/ls-lint-linux-amd64"
          echo "b5a0d2e4427ad039fbc574551f17679f38f142b25d15e0e538769f8cf15af397  ls-lint-linux-amd64" | sha256sum -c
          chmod +x ls-lint-linux-amd64
          sudo mv ls-lint-linux-amd64 /usr/local/bin/ls-lint

      - name: Run ls-lint
        run: ls-lint
