name: QA Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Install backend dependencies
        working-directory: ./server
        run: |
          python3 -m venv .venv
          .venv/bin/pip install --upgrade pip
          pip install uv
          uv sync --frozen

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run QA checks
        run: make qa

      - name: Run end-to-end tests
        run: make e2e-test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            server/htmlcov
            frontend/coverage
            frontend/playwright-report
